version: '3'
services:
  web:
    restart: unless-stopped
    build: .
    ports:
    - "${PORT}:${PORT}"
    environment:
      - books_database_host=database
      - books_database_port
      - books_database_name
      - books_database_username
      - books_database_password
      - REDIS_PORT
      - REDIS_HOST=redis
      - REDIS_PASSWORD
      - PORT
    depends_on:
      - database
      - redis
    volumes:
    - ./certs/private_key.der:/etc/ssl/certs/private_key.der
    - ./certs/public_key.der:/etc/ssl/certs/public_key.der
    - ./certs/book.p12:/etc/ssl/certs/book.p12
  database:
    image: 'mysql:8.0.25'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
  redis:
    image: 'bitnami/redis:6.2'
    environment:
      - REDIS_PASSWORD


