INSERT INTO `users` VALUES ('user1','$2a$10$m2lkoVeNmlalQt8f.wWY4.RGW.QnmzMPHgvddF.0GWilPWm6ZfNSm',1);
INSERT INTO `users` VALUES ('user2','$2a$10$46cewQs76eU9j/b346wKzOp2GPFZNT48AioQ3oBYQKDUDfClmrbD6',1);
INSERT INTO `users` VALUES ('user3','$2a$10$ozdI0wI6MmCJKrOsohrAgOPjM6BgFcqlhtuRAXF5/ImsAKskb.IMe',1);
INSERT INTO `users` VALUES ('user4','$2a$10$U41lHsYnJTqAsIz4aQJLZ.KB.jkeP7rzJXxMABbgvE.RSNYKymmFa',1);

INSERT INTO `books` VALUES (1,'Brave new world','Aldous Huxley','Originally published in 1932, this outstanding work of literature is more crucial and relevant today than ever before. Cloning, feel-good drugs, antiaging programs, and total social control through politics, programming, and media -- has Aldous Huxley accurately predicted our future? With a storyteller\'s genius, he weaves these ethical controversies in a compelling narrative that dawns in the year 632 AF (After Ford, the deity). When Lenina and Bernard visit a savage reservation, we experience how Utopia can destroy humanity. A powerful work of speculative fiction that has enthralled and terrified readers for generations, Brave New World is both a warning to be heeded and thought-provoking yet satisfying entertainment. - Container.','user1','public');
INSERT INTO `books` VALUES (2,'Nineteen Eighty-Four','George Orwell','Which One Will YOU Be IN the Year 1984? There won\'t be much choice, of course, if this book\'s predictions turn out to be true. But you\'ll probably become one of the following four types: Proletarian--Considered inferior and kept in total ignorance, you\'ll be fed lies from the Ministry of Truth, eliminated upon signs of promise or ability! Police Guard--Chosen for lack of intelligence but superiour brown, you\'ll be suspicious of everyone and be ready to give your life for Big Brother, the leader you\'ve never even seen! Party Member--Male--Face-less, mind-less, a flesh-and-blood robot with a push-button brain, you\'re denied love by law, taught hate by the flick of a switch! Party Member--Female--A member of the Anti-Sex League from birth, your duty will be to smother all human emotion, and your children might not be your husband\'s! Unbelievable? You\'ll feel differently after you\'ve read this best-selling book of forbidden love and terror in a world many of us may live to see!','user1','private');
INSERT INTO `books` VALUES (3,'Vingt mille lieues sous les mers','Jules Verne','A nineteenth-century science fiction tale of an electric submarine, its eccentric captain, and undersea world, which anticipated many of the scientific achievements of the twentieth century.','user1','public');
INSERT INTO `books` VALUES (4,'The Time Machine','H. G. Wells','The Time Traveller, a dreamer obsessed with traveling through time, builds himself a time machine and, much to his surprise, travels over 800,000 years into the future. He lands in the year 802701: the world has been transformed by a society living in apparent harmony and bliss, but as the Traveler stays in the future he discovers a hidden barbaric and depraved subterranean class. Wells\'s transparent commentary on the capitalist society was an instant bestseller and launched the time-travel genre.','user2','private');
INSERT INTO `books` VALUES (5,'The War of the Worlds','H. G. Wells','The ultimate science fiction classic: for more than one hundred years, this compelling tale of the Martian invasion of Earth has enthralled readers with a combination of imagination and incisive commentary on the imbalance of power that continues to be relevant today. The style is revolutionary for its era, employing a sophisticated first and third person account of the events which is both personal and focused on the holistic downfall of Earth\'s society. The Martians, as evil, mechanical and unknown a threat they are, remain daunting in today\'s society, where, despite technology\'s mammoth advances, humanity\'s hegemony over Earth is yet to be called into question. In Well\'s introduction to the book, where the character discusses with the later deceased Ogilvy about astronomy and the possibility of alien life defeating the \'savage\' (to them) nineteenth-century Britain, is he insinuating that this is the truth and fate of humanity? It\'s up to you to decide....','user2','private');
INSERT INTO `books` VALUES (6,'The Invisible Man','H. G. Wells','This book is the story of Griffin, a scientist who creates a serum to render himself invisible, and his descent into madness that follows.','user2','private');
INSERT INTO `books` VALUES (8,'Flatland','Edwin Abbott Abbott','Flatland: A Romance of Many Dimensions, though written in 1884, is still considered useful in thinking about multiple dimensions. It is also seen as a satirical depiction of Victorian society and its hierarchies. A square, who is a resident of the two-dimensional Flatland, dreams of the one-dimensional Lineland. He attempts to convince the monarch of Lineland of the possibility of another dimension, but the monarch cannot see outside the line. The square is then visited himself by a Sphere from three-dimensional Spaceland, who must show the square Spaceland before he can conceive it. As more dimensions enter the scene, the story\'s discussion of fixed thought and the kind of inhuman action which accompanies it intensifies.','user3','public');
INSERT INTO `books` VALUES (9,'A journey to the centre of the earth','Jules Verne','Three explorers descend to the center of the earth, where they encounter tumultuous storms, wild prehistoric animals, and fierce cavemen.','user3','public');
INSERT INTO `books` VALUES (10,'A Wrinkle in Time','Madeleine L\'Engle','Meg Murry and her friends become involved with unearthly strangers and a search for Meg\'s father, who has disappeared while engaged in secret work for the government.','user3','public');
INSERT INTO `books` VALUES (11,'The giver','Lois Lowry','Given his lifetime assignment at the Ceremony of Twelve, Jonas becomes the receiver of memories shared by only one other in his community and discovers the terrible truth about the society in which he lives.','user4','public');
INSERT INTO `books` VALUES (12,'El Mundo Perdido','Michael Crichton','HAN PASADO SEIS ANOS DEL DESASTRE EN PARQUE JURASICO, ANOS DESDE QUE AQUEL EXTRAORDINARIO SUENO DE CIENCIA E IMAGINACION LLECO A SU FINAL ESTREPITOSO: LOS DINOSAURIOS ANIQUILADOS, EL PARQUE DESMANTELADO, LA ISLA CERRADA AL PUBLICO POR TIEMPO INDEFINIDO.','user4','public');
INSERT INTO `books` VALUES (13,'The blind assassin','Margaret Atwood','More than fifty years on, Iris Chase is remembering Laura\'s mysterious death. And so begins an extraordinary and compelling story of two sisters and their secrets. Set against a panoramic backdrop of twentieth-century history, The Blind Assassin is an epic tale of memory, intrigue and betrayal...','user4','public');

